version: "3.7"

services:
  db:
    image: postgres:12
    environment:
      POSTGRES_DB: chugokudb
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
    volumes:
      - ./data:/var/lib/postgresql/data:delegated
      - ./work:/docker-entrypoint-initdb.d/:delegated
    ports:
      - "5436:5432"
    container_name: chugoku_pgsql
      
